### PR TITLE
added --node flag to init cmd

### PR DESCRIPTION
**Pull request by rafapaezbas**

### CODE REVIEW

**Comment by mafintosh** [comment]
killer

**Review by mafintosh — APPROVED** [review]

**Comment by mattdesl** [comment]
there is a discrepancy, two modules exist but carry different versions on npm. is that intentional?

```
     'bare-fs': '^2.1.5',
     fs: 'npm:bare-node-fs',
```

**Comment by mattdesl** [comment]
oh, confusing - all the dependencies are like that. there are two versions on npm of each? is that documented anywhere?

**Comment by mafintosh** [comment]
documented here https://github.com/holepunchto/bare-node

**Comment by mattdesl** [comment]
Perhaps an alias or import resolution map feature would be useful. The current approach seems prone to errors and lagging behind the base bare-x modules.

**Comment by mafintosh** [comment]
yea on our radar, would set the process object also.

**Pull request merged**
